eksctl create cluster \
--name my-prod-3 \
--version 1.17 \
--region eu-north-1 \
--nodegroup-name small-workers \
--node-type t3.small \
--nodes 2 \
--nodes-min 1 \
--nodes-max 3 \
--ssh-access \
--ssh-public-key ~/.ssh/public-production-cluster-key.pem \
--managed