apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-sample-ns
spec:
  type: LoadBalancer
  selector:
    app: blue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80