apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-sample-ns
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: poll
        image: ybsnek/poll
        ports:
        - containerPort: 80