apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: my-sample-ns
  labels:
    app: blue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
      - name: poll
        image: nginx:1.14.2
        ports:
        - containerPort: 80